alt_send_esc = false
background_opacity = 1

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "E"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Copy"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "Up"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "Down"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "Left"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "Right"
mode = "Vi"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key6"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "High"
key = "H"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Middle"
key = "M"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Low"
key = "L"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SemanticLeft"
key = "B"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRight"
key = "W"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "E"
mode = "Vi"

[[keyboard.bindings]]
action = "WordLeft"
key = "B"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRight"
key = "W"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRightEnd"
key = "E"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Bracket"
key = "Key5"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mode = "~Vi"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = ""
key = "Left"
mods = "Alt"

[general]
live_config_reload = true

[terminal]

[colors.bright]
black = "#7f8c8d"
blue = "#3daee9"
cyan = "#16a085"
green = "#1cdc9a"
magenta = "#8e44ad"
red = "#c0392b"
white = "#ffffff"
yellow = "#fdbc4b"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#31363b"
blue = "#1b668f"
cyan = "#186c60"
green = "#17a262"
magenta = "#614a73"
red = "#783228"
white = "#63686d"
yellow = "#b65619"

[colors.normal]
black = "#232627"
blue = "#1d99f3"
cyan = "#1abc9c"
green = "#11d116"
magenta = "#9b59b6"
red = "#ed1515"
white = "#fcfcfc"
yellow = "#f67400"

[colors.primary]
background = "#000000"
bright_background = "#000000"
bright_foreground = "#ffffff"
dim_background = "#31363b"
dim_foreground = "#eff0f1"
foreground = "#ffffff"

[colors.search.bar]
background = "#c5c8c6"
foreground = "#1d1f21"

[colors.search.focused_match]
background = "CellForeground"
foreground = "CellBackground"

[colors.search.matches]
background = "#ffffff"
foreground = "#7f8c8d"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 7.0
use_thin_strokes = false

[font.bold]
family = "Terminus (TTF)"
style = "Bold"

[font.bold_italic]
family = "Terminus (TTF)"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Terminus (TTF)"
style = "Italic"

[font.normal]
family = "Terminus (TTF)"
style = "Regular"

[scrolling]
history = 30000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>	'''

[terminal.shell]
args = ["--login"]
program = "/usr/local/bin/bash"

[url]
modifiers = "None"

[url.launcher]
program = "open"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[window.padding]
x = 7
y = 7

[keyboard]
